### ISSUE TITLE
jar包缺失

### ISSUE THREAD

**Issue by ElianWang** [ZHENFENG13/ssm-demo#1]
Error reading file C:\Users\Wow_fang
![1489462108 1](https://cloud.githubusercontent.com/assets/26395944/23884985/48f978e4-08ab-11e7-8d0c-2d072c3b86b7.png)
\.m2\repository\org\slf4\slf4j-api\20160310\slf4j-api-20160310.jar
C:\Users\Wow_fang\.m2\repository\org\slf4\slf4j-api\20160310\slf4j-api-20160310.jar (系统找不到指定的文件。)

**Comment by ZHENFENG13** [comment]
可能是版本号问题，你到这里http://mvnrepository.com/artifact/org.slf4j/slf4j-api
看你需要哪个版本，修改一下pom文件里的版本号应该就好了
