### ISSUE TITLE
博主,您好, 我在GitHub提交了一个版本,首页为何没有显示呢?

### ISSUE THREAD

**Issue by caochenhins** [ZHENFENG13/ssm-demo#3]
博主,您好, 我在GitHub提交了一个版本,

为何没有显示出来呢?
 
 
![qq 20170412134511](https://cloud.githubusercontent.com/assets/7531570/24942947/bd2ac7b2-1f86-11e7-8612-88bb91b1ede0.png)

**Comment by caochenhins** [comment]
![qq 20170412134511](https://cloud.githubusercontent.com/assets/7531570/24943044/3320a6f8-1f87-11e7-803d-a292b70ac644.png)

**Comment by ZHENFENG13** [comment]
是不是没有push到仓库，如果你用的是idea的话，可以command+shift+k提交

**Comment by ZHENFENG13** [comment]
git和svn不同，还有一步操作的

**Comment by caochenhins** [comment]
O(∩_∩)O谢谢, 知道了,提交失败,提示没有权限~.	Push failed: Failed with error: unable to access 'https://github.com/ZHENFENG13/ssm-demo.git/': The requested URL returned error: 403
我修改了百度编辑器的maven引用.如下: 
<dependency>
           groupId: <groupId>cn.songxinqiang</groupId>
           artifactId: <artifactId>com.baidu.ueditor</artifactId>
           version: <version>1.1.2-edit-1.0</version>
  </dependency>
因为Intellj编译时提示获取失败. 改为1.1.2-edit-1.0 就能获取了.^_^

**Comment by ZHENFENG13** [comment]
O(∩_∩)O你提交到你的仓库就行了

**Comment by ZHENFENG13** [comment]
百度地图？

**Comment by caochenhins** [comment]
好的.  是富文本编辑器~ ☺_☺

**Comment by ZHENFENG13** [comment]
那你可以pull requests到我这边

**Comment by caochenhins** [comment]
<groupId>com.baidu.ueditor</groupId>
            <artifactId>ueditor</artifactId>
            <version>20160310</version>
在intellj 2016.3.4下,改为以下配置即可编译通过:

            <groupId>cn.songxinqiang</groupId>
            <artifactId>com.baidu.ueditor</artifactId>
            <version>1.1.2-edit-1.0</version>
您看看pull这段代码是否合适, 也许和我的maven 版本有关.(3.3.9)

**Comment by ZHENFENG13** [comment]
嗯，maven仓库问题，我用的是私服，所以能找到jar包，你pull过来吧，不止一个人说这个jar包问题了，本来我也想改了

**Comment by caochenhins** [comment]
好的~ 学习啦~ 已经发起pull request,请您审核
